$(document).ready(function(){
    $("#first").click(function(){
        $("#two").hide();
        $("#three").hide();
        $("#four").hide();
        $("#five").hide();
        $("#one").fadeIn(2000);
        $("#ctone").css("display","block");
    });
    $("#second").click(function(){
        $("#one").hide();
        $("#three").hide();
        $("#four").hide();
        $("#five").hide();
        $("#two").fadeIn(2000);
        $("#cttwo").css("display","block");
    });
    $("#third").click(function(){
        $("#one").hide();
        $("#two").hide();
        $("#four").hide();
        $("#five").hide();
        $("#three").fadeIn(2000);
        $("#ctthree").css("display","block");
    });
    $("#fourth").click(function(){
        $("#one").hide();
        $("#two").hide();
        $("#three").hide();
        $("#five").hide();
        $("#four").fadeIn(2000);
        $("#ctfour").css("display","block");
    });
    $("#fifth").click(function(){
        $("#one").hide();
        $("#two").hide();
        $("#three").hide();
        $("#four").hide();
        $("#five").fadeIn(2000);
        $("#ctfive").css("display","block");
    });
});